# Generated by Django 5.1.1 on 2024-09-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
