# Generated by Django 5.1.1 on 2024-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_birth_date_customer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
