# Generated by Django 5.1.2 on 2024-10-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
